version: "3.6"
services:
    app:
        image: ghcr.io/mufid-experiments/requestbin:latest
        environment:
            REALM: prod
            REDIS_URL: "//redis:6379"
        links:
            - redis
        ports:
            - "8080:8080"
        deploy:
            restart_policy:
                condition: any

    redis:
        image: redis
        deploy:
            restart_policy:
                condition: any
